FROM node:lts-alpine AS build
WORKDIR /build
COPY . ./
RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn \
    yarn && yarn build
    
FROM httpd:alpine
WORKDIR /usr/local/apache2/htdocs/
COPY --from=build /build/build/ .